### ISSUE TITLE
Tracking Issue: Backend

### ISSUE THREAD

**Issue by reiner-dolp** [comprakt/comprakt#171]
Every contributor can edit this list directly. Please edit directly instead of posting comments below. 

- [x] **Merge Optimization Phase** (PR #165)
  - [x] Fix compiler and clippy warnings in libfirm-rs: All `clippy::perf` and `clippy::style` warnings are disabled. The final version should only suppress `dead_code` warnings and unreasonable `clippy::style` warnings like `let_and_return` and not th#174e whole category. Fixed in commit range 6632f15..eacceab.#174#174#174#174
  - [x] Clippy warns that our `Hash` Implementation on `Node` might be incompatible with the auto-derived `PartialEq`. I think in the current state of the code, this is a false positive, but another person should take a look and implement it manually. Fixed in commit 4d18b94.
  - [x] the fix for `MIN_INT` (PR #159) in master introduces extra `Conv` nodes which break constant folding of division and reminder.  Fixed in commits 95517903d99b and 6148ece6.
  - [ ] address issues we received per email from sebastian
    - [x] fix `return x = y;` (PR #166)
    - [x] phi nodes in constant folding should use join instead of `lhs == rhs`. Especially since `TargetValue.getBad() == TargetValue.getUnknown()`. Seems to be our Equality implementation, not libfirm. Probably fixed in commit 92a28e254e5, but needs test.
    - [ ] fold `0 * x` to `0`. This is trivial, you just have to keep the data dependency to the division node, which will ensure that the side effect is executed (and the division not dropped like the rest of the folded `x`).
  - [ ] Call `remove_unreachable_code()` not only `remove_bads()`
- [x] **Cleanup Cli Interface for Optimizations** (PR #174)
  - [x] `-O ''` for no optimizations is weird. Introduce `--no-optimiziations` instead.
  - [x] make `--optimization` a developer flag. Maybe it should only be available in debug mode or with a special env var set during compilation. Come up with a prefix for developer options, e.g. `--dev-` or `--internal`.
   - [x] optimizations should not perform fixpoint iterations. Come up with a more elaborate scheme.
   - [x] `dy` as a flag for `dump yComp graph` is pretty obscure. Maybe make it a single letter `d` for dump and add a long form `dump-graph` or similar.
    - [x] `dy` should respect dump folder
- [x] **Interactive Debugging for FIRM graphs** (PR #174)
   Otherwise no one will write more complex optimizations
- [ ] **Backend**
  - [ ] Find a way to test the backend code generation
    - [ ] Assert our backend has same stdout/stderr/exitcode as libfirm backend => correct/incorrect
    - [ ] Assert molki has same stdout/stderr/exitcode as libfirm backend => correct/register allocator incorrect
    - [ ] Additional or better ideas?
  - [ ] **Instruction selection and scheduling:** minimal implementation with 1:1, and 1:n for some cases, e.g. division
       - [ ] We want to model instructions using an enum that has a x86-instruction as variants, with an unlimited amount of registers.
       - [ ] Each AST instruction can be transformed to a list of x86-instructions.
          - [ ] Div instruction list from slides
          - [ ] Function preamble and postamble from slides
       - [ ] This means each basic block has a list of x86-instructions represented as a list of enums, which  you can compute by topological sort (= reverse postorder) of the nodes in the basic block.
       - [ ] (optional) optimize order of basic blocks to minimize (conditional) jumps
       - [ ] (optional) consider instruction scheduling for parallelizable subtrees like `a + b + c`. Instructions can be arbitrarily reordered between to (blue) memory edges.
       - [ ] (optional) substitute instructions for '*2^X' to use shifts.
       - [ ] ...
       - [ ] Deal with cycles formed by data dependencies (phi functions)
           - [ ] lost copy
           - [ ] critical edges
           - [ ] simultanious evaluation of phi vars
       - [ ] Deal with cycles formed by control flow dependencies (cyclic jumps)
       - [ ] Add simple transform in memory instruction lists to molki strings and assembly, e.g. via a newtype with Display implementation. code for basic block labeling can be found in slides. Everything can be emitted into the `.text` segment
       - [ ] At this step our representation is trivially transformable to Molkis representation. Write some automated tests.
  - [ ] **Resource Allocation/Register Selection**
    - [ ] Activation Records. A lot of code on the slides
    - [ ] Implement Chaitin as initial register allocator.
  - [ ] **Peephole Optimization**
    - Clone the GCC source code, grep for `define_peephole` in *.md files for some inspiration.
    - Libfirm has `cmp $0, %reg -> test %reg, %reg`, `lea c(%r), %r -> add $c, %r`, `lea (%r1, %r2), %r1 -> add %r2, %r1`, `lea (%r1, %r2), %r2 -> add %r1, %r2`, `mov $0, %reg -> xorl %reg, %reg`

**Comment by problame** [comment]
I would like to close this tracking issue and use the https://github.com/comprakt/comprakt/projects/2 board instead. @flip1995  ok?

**Comment by problame** [comment]
(Needless to say I copied all relevant open points to note cards in the board).
