### ISSUE TITLE
Tracking issue: What to take care of in the semantic analysis

### ISSUE THREAD

**Issue by flip1995** [comprakt/comprakt#84]
If something is being worked on in a PR or issue, link to it in the respective enum item.

---

During Name Analysis:
- [x] Exactly one static function
  - [x] static function  is called `main`
  - [x] argument of static function is used in `main` body
  - [x] argument of static function is redefined in `main` body
  - [x] this pointer inside static methods
  - [x] access on non-static methods
  - [x] access on non-static fields
- [x] ~If a class definition of `class String` exists, make sure it is used in the type check of `main`'s arguments.~ (Main arg as `String` is a syntactical feature in MJ) ~Java fails at runtime (not compile time) with 'Main method not found' error [demo here](https://repl.it/repls/EllipticalDimwittedNetworks))~ (In the semantical exceptions for MJ it says that exactly a single main method must exist => compile-time)
- [x] `ExpressionStatements` that are neither method calls nor assignments must be rejected

Before/During Type Check:
- [x] `main` must not be called
- [x] `System.out.println()` Edge cases
  - If `System` is undefined, use stdlib-system
  - If `System` is defined as a local variables => shadow (this is the easy case)
  - If `System` is defined as a type (`class System {}`) => fail (this is the edge case)
- [x] return inside functions on every path
- [x] `Expr` Type check.
- [x] l-value check

Other things:
- [x] Not a statement errors in java. 
- [x] `null` type ?
  - [x] comparisons of references to `null` must be allowed
  - [x] comparisons of primitves to `null` must be forbidden
  - [x] comparisons of arrays to `null` must be allowed
- [x] `void[][]`
- [x] try parse `IntLit` to `i32`

UB to handle:
- [x] ~~Usage of undefined variables (Definite Assignment Rule)~~ see #107 
- [x] ~~`null` access and div by 0~~ see #108 and #109 
- [x] ~~index out of bounds array access~~ see #110

**Comment by reiner-dolp** [comment]
especially, exactly 1 main function exists.

**Comment by flip1995** [comment]
Everyone can edit the OP

**Comment by reiner-dolp** [comment]
Probably should also disallow redefining String.

**Comment by reiner-dolp** [comment]
assigning to this should be disallowed.

**Comment by flip1995** [comment]
Everything handled or moved to another Issue
